- index.html
- src/components/main.js
- src/styles/common.css
- src/styles/main.css
* 배경 음악 추가, 버튼 누를 시 mute 토글
* 모드 버튼 클릭시 모드 선택 모달 나타남
* 무슨 모드로 시작하는지 판별
* #3 
* 가이드 모드 선택시 모듈 나타납니다.
- play화면으로 이동 `url`
```
url: /origami/play
```
```js
const navigateToPlay = () => {
const $activeGuideModeButton = document.querySelector('.guide-mode.active');
const modalOpacity = parseFloat(getComputedStyle($modeModal).opacity);
if (modalOpacity !== 0) {
const guideMode = $activeGuideModeButton.getAttribute('data-mode');
window.location.href = `/play-${guideMode}`;
} else {
window.location.href = '/play';
}
};
```
sandbox모드일 때는 '/play' 로 이동, guide모드일 때는 `/play-${guideMode}` 로 이동합니다. 해당 부분 확인하여 나중에 작업해주시면 될 듯 합니다.
> #3 메인 페이지 기능 구현

- completePage.html
- package-lock.json
- package.json
- play.html
- src/components/origami.js
- src/components/play.js
- src/styles/completePage.css
- src/styles/play.css
- src/three/Renderer.js
- src/three/Sizes.js
- Restart 클릭 시 홈화면으로 이동
- finish 클릭 시 원래 종이접기 완성된 종이접기 Y축기준 회전하는 애니메이션 반복
- 애니메이션 뒤로 confetti 애니메이션 반복
* #17 
다만 우클릭은 x (카메라 위치 고정)
- 종이 폭죽 구현을 위해 [js-confetti 라이브러리](https://www.npmjs.com/package/js-confetti?activeTab=readme) 사용
> #17 완료 페이지 기능 구현

- src/components/modules/debounce.js
- src/components/modules/foldingAnimation.js
- src/components/modules/origami.js
- debounce 함수 추가해 미리보기 연산이 마우스가 움직일 때 마다 일어나지 않도록 수정했습니다.
- #42 
미리보기 기능 최적화
- debounce함수 모듈화 해놓았으니 필요한 함수에 가져다 쓰면 됩니다.
> #44 미리보기 기능 최적화

- .gitignore
- firebase.js
- package-lock.json
- package.json
- play.html
- src/components/gallery.js
- src/components/modules/guideModules.js
- src/components/modules/guideSlide.js
- src/components/modules/origami.js
- src/components/modules/showToastMessage.js
- src/components/play.js
- src/components/services/userService.js
- src/constants/guide.js
- src/constants/index.js
- src/styles/completePage.css
- src/styles/play.css
- src/three/Paper.js
- src/three/Renderer.js
- SHARE 버튼 클릭하면 firebase의 firestore에 해당 데이터들을 저장합니다.
- 썸네일 캡쳐를 위한 html2canvas 라이브러리 추가되었으니 npm install 하세요!
- 파이어베이스 관련 정보 환경변수로 저장했으니 환경변수 파일 만드셔야합니다.
- #18 
```window.location.href = `/gallery?id=${userId}```
- 파이어베이스의 데이터 저장 크기 제한이 있어 정점을 청크화했습니다.
```
데이터 청크화 (Chunking):
데이터를 여러 청크(chunk)로 나누어 저장합니다. 예를 들어 정점 데이터를 100개씩 나누어 여러 문서에 저장할 수 있습니다.
이 방식은 Firebase에서 문서 크기 제한을 피할 수 있고, 데이터 읽기와 쓰기 성능을 최적화할 수 있습니다.
각 청크는 고유한 식별자를 가지고 있어야 하며, 필요할 때 모든 청크를 병합하여 원래 데이터를 복원할 수 있어야 합니다.
```
나중에 gallery 페이지에서 데이터를 불러올 때 청크화 된 positions의 값들을 병합하는 과정이 필요합니다!
> #18 공유 버튼 클릭 시 파이어베이스에 정보 저장

- src/components/gallery.js
- src/components/modules/origami.js
- src/constants/index.js
- 중복된 코드 있는 부분 수정, 삭제
- - shareButton 관련 중복된 기능을 수행하는 부분 정리했습니다.
- - toastMessage 관련 중복된 기능을 수행하는 부분 정리했습니다.
- #18
> #18 머지 후 버그 수정

- src/components/gallery.js
- src/components/modules/origami.js
- src/components/modules/prevNextButtons.js
- src/constants/index.js
- 펼쳤을 때 borderVertex 업데이트 되지 않는 버그 수정했습니다.
- #18 
- 현재 펼치기는 history에 저장되지 않는 버그 있으며, 가이드 데이터 구축 된 PR 받은 후 수정할 예정입니다.
> #18 펼치기 정점 버그 수정

- src/components/modules/foldingVertexPosition.js
- src/components/modules/guideModules.js
- src/components/modules/origami.js
- src/constants/guide.js
- 변경사항 내용 작성
-  [가이드모드 데이터 구축](https://github.com/orgs/Origami-5M/projects/1?pane=issue&itemId=69231581)
되돌리기 기능 이후 화면이 정지가 되는 이슈가 있습니다.
> #45 비행기 가이드모드 데이터 구축

- src/components/play.js
- 재시작 버튼 동적으로 모드에 맞게 시작하도록 수정했습니다.
- #15
> #15 재시작 버튼 기능 구현

- src/components/modules/foldingVertexPosition.js
- src/components/modules/guideModules.js
- src/components/modules/origami.js
- src/components/modules/rotateSelectedVertices.js
- src/constants/guide.js
> #59 강아지 가이드 모드 데이터 구축

- src/components/modules/guideModules.js
비행기 모드 z-fighting 해결변경사항 내용 작성
[비행기 가이드 모드 에러 픽스](https://github.com/orgs/Origami-5M/projects/1/views/1?pane=issue&itemId=69475509)
비행기 모드 접기 시 z-fighting 이 일어나는 부분 해결
> 비행기 가이드 모드 에러 픽스

- src/styles/common.css
> #61 body 스타일 삭제

- src/styles/common.css
> #61 배포시 문제되는 css삭제

- .gitignore
- package-lock.json
- package.json
- src/components/tests/main/main.test.js
- vitest.config.js
- vitest 환경 설정
``` text
**npm i 꼭 하고 시작하세요**
```
- [테스트 코드 작업 분배 링크](https://www.notion.so/8-14-c27a11ef1a87427ca31b232636cb81ff)
[x] 테스트 코드 환경 설정
> #78 vitest 환경 설정

- src/components/gallery.js
- src/components/tests/gallery/gallery.test.js
File                             | % Stmts | % Branch | % Funcs | % Lines |
gallery.js                    |   68.36   |        63.33 |         100 |    68.36 |
loadingSpinner.js      |          84 |             50 |          100 |         84 |
Sizes.js                      |     61.53 |                0 |          100 |    61.53 |
- #81
> ✅ Test: #81 gallery.js 테스트코드 작성

- src/components/mobileRedirect.js
- src/components/modules/axisCalculations.js
- src/components/tests/axios/axisCalculations.test.js
- src/components/tests/mobileRedirect/mobileRedirect.test.js
File                             | % Stmts | % Branch | % Funcs | % Lines |
mobileRedirect.js     |      66.66 |            100 |         100 |    66.66 |
axisCalculations.js   |      95.85 |        95.65 |          100 |    95.85 |
- #21
> Test/#21 mobileRedirect.js, axisCalculations.js 테스트 코드 작성

- src/components/modules/guideSlide.js
- src/components/play.js
- src/components/tests/gallery/gallery.test.js
- src/components/tests/play/play.test.js
File | % Stmts | % Branch | % Funcs | % Lines |
play.js   |   69.07 |    55.55 |   85.71 |   69.07 |
- #87
> #85 play.js 테스트코드 작성

- src/components/tests/rotateSelectedVertices/rotateSelectedVertices.test.js
File | % Stmts | % Branch | % Funcs | % Lines |
rotateSelectedVertices.js      |   73.33 |    81.81 |     100 |   73.33 |
- #94
> #94 rotateSelectedVertices.js 테스트코드 작성

- src/components/tests/modules/debounce.test.js
- src/components/tests/modules/findClosestVertex.test.js
File                             | % Stmts | % Branch | % Funcs | % Lines |
debounce.js                    |   91.66 |      100 |     100 |   91.66 |
findClosestVertex.js           |     100 |      100 |     100 |     100 |
- #91
> #91 debounce.js, findClosestVertex.js 테스트코드 작성

- src/components/tests/foldingVertexPosition/foldingVertexPosition.test.js
File                             | % Stmts | % Branch | % Funcs | % Lines |
foldingVertexPosition.js       |   70.58 |       60 |      75 |   70.58 | 
- #96
> #96 foldingVertexPosition.js 테스트코드 작성

- README.md
> 📝 Docs: README.md update

- src/components/services/getUserService.js
- Promise.all 활용하여 병렬 처리 로직 구현하여 불러오는 기능 최적화
- #100
> #100 3D 데이터 불러오는 기능 최적화

- src/components/three/PaperCanvas.jsx
- src/components/three/PointsMarker.jsx
- pointsMarker의 mesh를 three.js => R3F로 변경했습니다.
> Points marker 메쉬 R3F로 변경

- src/components/three/ClosestVertex.jsx
- src/components/three/Paper.jsx
- src/components/three/PaperCanvas.jsx
- src/components/three/computeBoundaryPoints.js
- src/components/three/paperUtils.js
- src/constants/paper.js
- findClosestVertex 함수 생성하여 borderVertices 구하여 가까운 좌표 찾기 로직 구현
- computeBoundaryPoints 함수 통해서 종이의 가장자리 좌표 판별
- calculateRotatedLine 함수 생성하여
- extendToBoundary 함수 생성하여 주어진 midpoint에서 direction 방향으로 경계를 확장
- findIntersection 함수 생성하여 주어진 midpoint에서 특정 방향으로 나아갈 때, 경계선과의 교차점을 찾음
- updateBoundaryAndAxis 함수를 생성하여 접는 축 생성
- isInteracting 상태를 조작하여 MouseUp 시 OrbitControls 할때 OrbitControls 비활성 로직 구현
- raycaster를 통해 클릭한 좌표 가져오기
- handlePointerEvent 함수를 통해 마우스의 3D 좌표 판별
- BorderPoints 함수를 통해 마우스 좌표와 가장 가까운 정점 판별
> Feat: 회전 축 생성 로직 구현
